/**
 * FullSendOS Self-Documentation Review System
 * Deterministic inventories of documentation and implementation.
 *
 * This is a static inventory — it describes the known state of the repo.
 * Update these inventories when new docs or implementation areas are added.
 * No live AI calls. No secrets. No runtime data.
 */

import type { DocInventoryItem, ImplementationInventoryItem } from "./types";

export const DOC_INVENTORY: DocInventoryItem[] = [
  {
    path: "README.md",
    title: "Consulting OS Foundation README",
    category: "other",
    topics: ["quick start", "overview"],
    statusMarkers: [],
    relatedAreas: ["all"],
    riskLevel: "medium",
    notes: "Root README; may be outdated relative to current feature set.",
  },
  {
    path: "ARCHITECTURE.md",
    title: "Architecture Overview",
    category: "architecture",
    topics: ["architecture", "system design"],
    statusMarkers: [],
    relatedAreas: ["app", "services", "schemas"],
    riskLevel: "high",
    notes: "Root-level ARCHITECTURE.md; may duplicate docs/ARCHITECTURE.md — review for conflicts.",
  },
  {
    path: "docs/ARCHITECTURE.md",
    title: "Architecture (docs/)",
    category: "architecture",
    topics: ["architecture", "api routes", "data flow"],
    statusMarkers: [],
    relatedAreas: ["app", "services", "schemas"],
    riskLevel: "high",
    notes: "May need updates for client baseline, demo workspace, guided tour, and deliverable readiness additions.",
  },
  {
    path: "docs/ROADMAP.md",
    title: "Roadmap",
    category: "roadmap",
    topics: ["roadmap", "planned features", "epics"],
    statusMarkers: ["planned", "in progress", "deferred"],
    relatedAreas: ["all"],
    riskLevel: "high",
    notes: "Likely stale — multiple implemented features (Executive OS UI, onboarding, demo, guided tour, deliverable quality) may not be reflected.",
  },
  {
    path: "docs/PROJECT_CONTEXT.md",
    title: "Project Context",
    category: "project-context",
    topics: ["vision", "context", "north star"],
    statusMarkers: [],
    relatedAreas: ["all"],
    riskLevel: "medium",
    notes: "Source of truth document; verify it reflects current product state.",
  },
  {
    path: "docs/VISION.md",
    title: "Vision",
    category: "vision",
    topics: ["vision", "product goals"],
    statusMarkers: [],
    relatedAreas: ["all"],
    riskLevel: "low",
    notes: "Vision docs are generally stable; review for any planned-but-shipped items.",
  },
  {
    path: "docs/CONTRIBUTING.md",
    title: "Contributing Guide",
    category: "contributing",
    topics: ["contributing", "dev workflow"],
    statusMarkers: [],
    relatedAreas: ["app", "services", "tests"],
    riskLevel: "low",
    notes: "Review for accuracy against current test commands and branch conventions.",
  },
  {
    path: "docs/DECISIONS.md",
    title: "Architecture Decisions",
    category: "other",
    topics: ["decisions", "architecture", "adr"],
    statusMarkers: [],
    relatedAreas: ["all"],
    riskLevel: "medium",
    notes: "Review whether new decisions (deliverable readiness model, self-documentation system) should be recorded here.",
  },
  {
    path: "docs/DEPARTMENTS.md",
    title: "Departments",
    category: "api",
    topics: ["departments", "AI Workforce", "pipeline"],
    statusMarkers: [],
    relatedAreas: ["departments", "services/workflow-engine.ts"],
    riskLevel: "medium",
    notes: "Verify department list matches actual workflow implementation.",
  },
  {
    path: "docs/ENGAGEMENTS.md",
    title: "Engagements",
    category: "api",
    topics: ["engagements", "projects", "workflow"],
    statusMarkers: [],
    relatedAreas: ["app/api/engagements"],
    riskLevel: "medium",
    notes: "May need update for client-linked engagement and lifecycle changes.",
  },
  {
    path: "docs/MEMORY.md",
    title: "Memory",
    category: "other",
    topics: ["memory", "context"],
    statusMarkers: [],
    relatedAreas: ["all"],
    riskLevel: "low",
    notes: "Review for accuracy.",
  },
  {
    path: "docs/AGENT_FRAMEWORK_EPIC.md",
    title: "Agent Framework Epic",
    category: "epic",
    topics: ["agent framework", "AI Workforce", "agent collaboration"],
    statusMarkers: ["planned", "epic"],
    relatedAreas: ["agents/", "services/workflow-agent-executor.ts"],
    riskLevel: "high",
    notes: "Agent framework is largely implemented. Review for items now complete vs. still planned.",
  },
  {
    path: "docs/agent-framework.md",
    title: "Agent Framework",
    category: "epic",
    topics: ["agent framework", "AI agents"],
    statusMarkers: [],
    relatedAreas: ["agents/"],
    riskLevel: "medium",
    notes: "May duplicate AGENT_FRAMEWORK_EPIC.md — review for overlap.",
  },
  {
    path: "docs/CLIENT_ONBOARDING_BASELINE_SPEC.md",
    title: "Client Onboarding Baseline Spec",
    category: "spec",
    topics: ["client onboarding", "ClientBaseline", "onboarding wizard"],
    statusMarkers: [],
    relatedAreas: ["schemas/client-baseline.ts", "services/client-baseline-store.ts", "app/clients/new/onboarding"],
    riskLevel: "low",
    notes: "Recently created. Review for accuracy against implementation.",
  },
  {
    path: "docs/EXECUTIVE_OS_UI_AUDIT.md",
    title: "Executive OS UI Audit",
    category: "audit",
    topics: ["Executive OS UI", "UX audit", "dashboard"],
    statusMarkers: [],
    relatedAreas: ["app/components/"],
    riskLevel: "low",
    notes: "Recently created. Current.",
  },
  {
    path: "docs/EXECUTIVE_OS_UI_SYSTEM.md",
    title: "Executive OS UI System",
    category: "spec",
    topics: ["Executive OS UI", "design system", "visual principles"],
    statusMarkers: [],
    relatedAreas: ["app/components/", "app/globals.css"],
    riskLevel: "low",
    notes: "Recently created. Current.",
  },
  {
    path: "docs/EXECUTIVE_OS_UI_SYSTEM_RESULTS.md",
    title: "Executive OS UI System Results",
    category: "results",
    topics: ["Executive OS UI", "results"],
    statusMarkers: [],
    relatedAreas: ["app/components/"],
    riskLevel: "low",
    notes: "Recently created. Current.",
  },
  {
    path: "docs/USABILITY_INTAKE_AUDIT.md",
    title: "Usability Intake Audit",
    category: "audit",
    topics: ["usability", "intake", "onboarding"],
    statusMarkers: [],
    relatedAreas: ["app/components/", "schemas/client-baseline.ts"],
    riskLevel: "low",
    notes: "Recently created. Current.",
  },
  {
    path: "docs/GROK_LIVE_VERIFICATION.md",
    title: "Grok Live Verification",
    category: "verification",
    topics: ["live Grok provider", "verification"],
    statusMarkers: [],
    relatedAreas: ["ai/grok-client.ts"],
    riskLevel: "low",
    notes: "Verification doc. PASS status recorded.",
  },
  {
    path: "docs/LIVE_GROK_AGENT_VERIFICATION.md",
    title: "Live Grok Agent Verification",
    category: "verification",
    topics: ["live Grok provider", "agent task", "collaboration"],
    statusMarkers: [],
    relatedAreas: ["agents/", "scripts/"],
    riskLevel: "low",
    notes: "Verification doc. PASS status recorded.",
  },
  {
    path: "docs/LIVE_GROK_WORKFLOW_SMOKE.md",
    title: "Live Grok Workflow Smoke",
    category: "verification",
    topics: ["live Grok provider", "workflow smoke test"],
    statusMarkers: [],
    relatedAreas: ["services/workflow-engine.ts"],
    riskLevel: "low",
    notes: "Verification doc. Current.",
  },
  {
    path: "docs/INTERNAL_DEMO_REVIEW_PACKAGE.md",
    title: "Internal Demo Review Package",
    category: "results",
    topics: ["demo workspace", "internal review"],
    statusMarkers: [],
    relatedAreas: ["services/demo-workspace.ts"],
    riskLevel: "low",
    notes: "Internal review package. Current.",
  },
  {
    path: "docs/INTERNAL_DEMO_ARTIFACT_INDEX.md",
    title: "Internal Demo Artifact Index",
    category: "results",
    topics: ["demo workspace", "artifacts"],
    statusMarkers: [],
    relatedAreas: ["services/demo-workspace.ts"],
    riskLevel: "low",
    notes: "Artifact index. Current.",
  },
  {
    path: "docs/SLICE-6-WORKFLOW-AGENTS.md",
    title: "Slice 6: Workflow Agents",
    category: "slice",
    topics: ["agent framework", "workflow agents"],
    statusMarkers: ["complete", "merged"],
    relatedAreas: ["services/workflow-agent-executor.ts"],
    riskLevel: "low",
    notes: "Completed slice doc.",
  },
  {
    path: "docs/SLICE-13-AGENT-DATA-ROOM-RETRIEVAL-PLAN.md",
    title: "Slice 13: Agent Data Room Retrieval Plan",
    category: "slice",
    topics: ["agent framework", "data room", "retrieval"],
    statusMarkers: ["planned", "plan"],
    relatedAreas: ["services/data-room-retrieval-service.ts"],
    riskLevel: "medium",
    notes: "Plan doc — may be partially implemented; verify status.",
  },
  {
    path: "docs/SLICE-EPIC1-CLIENT-DATA-ROOM.md",
    title: "Slice Epic 1: Client Data Room",
    category: "epic",
    topics: ["data room", "Client Data Room"],
    statusMarkers: ["complete", "epic"],
    relatedAreas: ["app/api/clients/[clientId]/data-room"],
    riskLevel: "low",
    notes: "Completed epic doc.",
  },
  {
    path: "docs/PROMPTS.md",
    title: "Prompts",
    category: "other",
    topics: ["prompts", "AI prompts"],
    statusMarkers: [],
    relatedAreas: ["departments/"],
    riskLevel: "medium",
    notes: "Review for accuracy against current department prompt implementations.",
  },
  {
    path: "docs/AGENT_COLLABORATION_FRAMEWORK.md",
    title: "Agent Collaboration Framework",
    category: "epic",
    topics: ["agent collaboration", "collaboration framework", "agent team selection", "Leadership Doctrine"],
    statusMarkers: ["v1", "implemented"],
    relatedAreas: ["lib/agents/", "ai/governance/"],
    riskLevel: "low",
    notes: "Agent Collaboration Framework v1 — recently implemented. Current.",
  },
  {
    path: "docs/AGENT_REGISTRY.md",
    title: "Agent Registry",
    category: "api",
    topics: ["agent registry", "agent profiles", "specialist agents"],
    statusMarkers: ["v1"],
    relatedAreas: ["lib/agents/agent-registry.ts"],
    riskLevel: "low",
    notes: "Recently created. Current.",
  },
  {
    path: "docs/FULLSENDOS_LEADERSHIP_DOCTRINE.md",
    title: "FullSendOS Leadership Doctrine",
    category: "other",
    topics: ["Leadership Doctrine", "governance", "operating principles"],
    statusMarkers: ["v1.0.0"],
    relatedAreas: ["ai/governance/leadership-doctrine.ts"],
    riskLevel: "low",
    notes: "Recently created. Current.",
  },
  {
    path: "docs/AGENT_COLLABORATION_RESULTS.md",
    title: "Agent Collaboration Results",
    category: "results",
    topics: ["agent collaboration", "results"],
    statusMarkers: [],
    relatedAreas: ["lib/agents/"],
    riskLevel: "low",
    notes: "Recently created. Current.",
  },
  {
    path: "docs/CLIENT_PORTAL_ACCESS_LAYER.md",
    title: "Client Portal Access Layer",
    category: "epic",
    topics: ["client portal", "client-safe visibility", "access layer"],
    statusMarkers: ["v1", "implemented"],
    relatedAreas: ["lib/client-portal/", "app/client-portal/"],
    riskLevel: "low",
    notes: "Client Portal Access Layer v1 — recently implemented. Current.",
  },
  {
    path: "docs/CLIENT_PORTAL_ACCESS_RESULTS.md",
    title: "Client Portal Access Results",
    category: "results",
    topics: ["client portal", "results"],
    statusMarkers: [],
    relatedAreas: ["lib/client-portal/"],
    riskLevel: "low",
    notes: "Recently created. Current.",
  },
  {
    path: "docs/LIVE_OS_AGENT_WORKFORCE_PREVIEW.md",
    title: "Live OS Agent Workforce Preview",
    category: "verification",
    topics: ["live os", "agent workforce", "collaboration trace", "owner admin"],
    statusMarkers: ["preview"],
    relatedAreas: ["app/components/work-product-viewer.tsx", "app/components/collaboration-trace-panel.tsx"],
    riskLevel: "low",
    notes: "Owner/Admin live workforce preview guidance and visibility rules.",
  },
  {
    path: "docs/LIVE_OS_AGENT_WORKFORCE_RESULTS.md",
    title: "Live OS Agent Workforce Results",
    category: "results",
    topics: ["live os", "agent workforce", "results"],
    statusMarkers: [],
    relatedAreas: ["app/components/work-product-viewer.tsx", "lib/agents/"],
    riskLevel: "low",
    notes: "Implementation and validation outcomes for live workforce preview slice.",
  },
  {
    path: "docs/OS_TEST_DRIVE_PREVIEW.md",
    title: "OS Test Drive Preview",
    category: "verification",
    topics: ["test drive", "preview", "OS readiness"],
    statusMarkers: ["ready-to-ship"],
    relatedAreas: ["all"],
    riskLevel: "low",
    notes: "OS Test Drive Preview after Agent Collaboration Framework v1 merge.",
  },
  {
    path: "docs/OS_FUNCTIONAL_TEST_DRIVE.md",
    title: "OS Functional Test Drive",
    category: "verification",
    topics: ["functional test", "manual QA"],
    statusMarkers: [],
    relatedAreas: ["all"],
    riskLevel: "low",
    notes: "Manual test drive doc.",
  },
  {
    path: "docs/OS_USE_READINESS.md",
    title: "OS Use Readiness",
    category: "verification",
    topics: ["readiness", "production readiness"],
    statusMarkers: [],
    relatedAreas: ["all"],
    riskLevel: "medium",
    notes: "Readiness doc — review against current feature set and known deferred items.",
  },
  {
    path: "docs/PREVIEW_DEMO_QA.md",
    title: "Preview Demo QA",
    category: "verification",
    topics: ["preview", "demo", "QA"],
    statusMarkers: [],
    relatedAreas: ["services/demo-workspace.ts"],
    riskLevel: "low",
    notes: "Demo QA doc.",
  },
];

export const IMPLEMENTATION_INVENTORY: ImplementationInventoryItem[] = [
  {
    path: "services/deliverable-readiness.ts",
    kind: "service",
    topics: ["deliverable readiness", "human review checklist", "client-readiness labeling"],
    relatedDocs: [],
    notes: "DEFERRED DOCS: CONSULTING_DELIVERABLE_QUALITY_AUDIT.md, CONSULTING_DELIVERABLE_STANDARD.md, CONSULTING_DELIVERABLE_QUALITY_RESULTS.md not yet created.",
  },
  {
    path: "services/demo-workspace.ts",
    kind: "service",
    topics: ["demo workspace", "Apex Brewing", "fictional demo data"],
    relatedDocs: ["docs/INTERNAL_DEMO_REVIEW_PACKAGE.md"],
    notes: "Demo workspace updated with richer deliverables, evidence, assumptions, open questions. No dedicated demo workspace spec doc.",
  },
  {
    path: "app/components/guided-tour.tsx",
    kind: "component",
    topics: ["guided tour", "onboarding tour"],
    relatedDocs: [],
    notes: "Guided tour implemented. No dedicated guided tour spec or results doc.",
  },
  {
    path: "app/api/demo/seed/route.ts",
    kind: "api-route",
    topics: ["demo workspace", "demo seed API"],
    relatedDocs: [],
    notes: "Demo seed API implemented. No API reference doc for demo endpoints.",
  },
  {
    path: "schemas/client-baseline.ts",
    kind: "schema",
    topics: ["client onboarding", "ClientBaseline"],
    relatedDocs: ["docs/CLIENT_ONBOARDING_BASELINE_SPEC.md"],
    notes: "Well-documented.",
  },
  {
    path: "services/client-baseline-store.ts",
    kind: "service",
    topics: ["client onboarding", "ClientBaseline"],
    relatedDocs: ["docs/CLIENT_ONBOARDING_BASELINE_SPEC.md"],
    notes: "Well-documented.",
  },
  {
    path: "app/components/first-run-dashboard.tsx",
    kind: "component",
    topics: ["Executive OS UI", "first-run experience", "demo workspace", "guided tour"],
    relatedDocs: ["docs/EXECUTIVE_OS_UI_SYSTEM.md", "docs/EXECUTIVE_OS_UI_AUDIT.md"],
    notes: "First-run experience documented in Executive OS UI system docs.",
  },
  {
    path: "services/deliverable-export-service.ts",
    kind: "service",
    topics: ["export", "PDF export", "export formatting", "deliverable quality"],
    relatedDocs: [],
    notes: "Export service updated with review notices and HTML polish. No standalone export architecture doc.",
  },
  {
    path: "ai/grok-client.ts",
    kind: "service",
    topics: ["live Grok provider", "xAI", "AI provider"],
    relatedDocs: ["docs/GROK_LIVE_VERIFICATION.md", "docs/LIVE_GROK_AGENT_VERIFICATION.md"],
    notes: "Well-documented via verification reports.",
  },
  {
    path: "services/workflow-engine.ts",
    kind: "service",
    topics: ["AI Workforce", "workflow engine", "departments"],
    relatedDocs: ["docs/DEPARTMENTS.md", "docs/SLICE-6-WORKFLOW-AGENTS.md"],
    notes: "Core workflow engine. Has partial docs.",
  },
  {
    path: "agents/",
    kind: "other",
    topics: ["agent framework", "agent collaboration", "AI agents", "collaboration framework"],
    relatedDocs: ["docs/AGENT_COLLABORATION_FRAMEWORK.md", "docs/AGENT_REGISTRY.md", "docs/AGENT_FRAMEWORK_EPIC.md", "docs/SLICE-6-WORKFLOW-AGENTS.md"],
    notes: "Agent Collaboration Framework v1 implemented. Docs now available.",
  },
  {
    path: "app/api/clients/[clientId]/baseline/route.ts",
    kind: "api-route",
    topics: ["client onboarding", "ClientBaseline", "API"],
    relatedDocs: ["docs/CLIENT_ONBOARDING_BASELINE_SPEC.md"],
    notes: "Well-documented.",
  },
  {
    path: "app/components/work-product-viewer.tsx",
    kind: "component",
    topics: ["Executive OS UI", "deliverable quality", "human review checklist", "readiness labeling"],
    relatedDocs: ["docs/EXECUTIVE_OS_UI_SYSTEM.md"],
    notes: "Readiness and checklist improvements not yet reflected in a deliverable-quality doc.",
  },
];

/** Features known to be implemented that should be searched for in docs. */
export const IMPLEMENTED_FEATURES = [
  "Live Grok provider",
  "AI Workforce",
  "agent collaboration",
  "Leadership Doctrine",
  "collaboration framework",
  "client onboarding",
  "ClientBaseline",
  "Data Room",
  "PDF export",
  "Executive OS UI",
  "demo workspace",
  "guided tour",
  "human review checklist",
  "client-readiness labeling",
  "deliverable readiness",
  "consulting deliverable quality",
  "self-documentation",
  "client portal",
  "client-safe visibility",
  "live os workforce preview",
] as const;

/** Deferred documentation items that should be detected as missing. */
export const KNOWN_DEFERRED_DOCS = [
  "CONSULTING_DELIVERABLE_QUALITY_AUDIT.md",
  "CONSULTING_DELIVERABLE_STANDARD.md",
  "CONSULTING_DELIVERABLE_QUALITY_RESULTS.md",
  "DEMO_WORKSPACE_SPEC.md",
  "GUIDED_TOUR_SPEC.md",
  "DELIVERABLE_READINESS_MODEL.md",
] as const;

/** Upcoming roadmap epics not yet implemented. */
export const UPCOMING_EPICS = [
  "Self-Documentation Review System",
  "Secure Client Portal Production Foundation",
  "Production Infrastructure",
  "Executive OS UI polish",
  "Owner/Admin workspace split",
] as const;
