/**
 * FullSendOS Self-Documentation Review System
 * Markdown report renderer.
 *
 * Renders a DocumentationReviewReport to a safe Markdown string.
 * No secrets, no runtime data, no provider payloads.
 */

import type { DocumentationReviewReport } from "./types";

const SEVERITY_LABELS: Record<string, string> = {
  high: "HIGH",
  warning: "WARNING",
  info: "INFO",
};

const TYPE_LABELS: Record<string, string> = {
  "stale-doc": "Stale Doc",
  "missing-doc": "Missing Doc",
  "implementation-undocumented": "Undocumented Implementation",
  "roadmap-status-mismatch": "Roadmap Status Mismatch",
  "architecture-mismatch": "Architecture Mismatch",
  "deferred-doc-needed": "Deferred Doc Needed",
  "decision-record-needed": "Decision Record Needed",
  "duplicate-or-overlapping-doc": "Duplicate/Overlapping Doc",
  "terminology-inconsistency": "Terminology Inconsistency",
};

export function renderReviewReportMarkdown(report: DocumentationReviewReport): string {
  const lines: string[] = [];

  lines.push(`# FullSendOS Documentation Review Report`);
  lines.push(``);
  lines.push(`> **Generated by:** FullSendOS Self-Documentation Review System`);
  lines.push(`> **Generated at:** ${report.generatedAt}`);
  lines.push(`> **Branch:** ${report.branch}`);
  lines.push(``);
  lines.push(`> ⚠️ **Human Approval Required** — ${report.guardrail}`);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  lines.push(`## Summary`);
  lines.push(``);
  lines.push(report.summary);
  lines.push(``);
  lines.push(`- Documentation files inventoried: **${report.docCount}**`);
  lines.push(`- Implementation areas inventoried: **${report.implementationAreaCount}**`);
  lines.push(`- Total findings: **${report.findings.length}**`);
  const high = report.findings.filter((f) => f.severity === "high").length;
  const warning = report.findings.filter((f) => f.severity === "warning").length;
  const info = report.findings.filter((f) => f.severity === "info").length;
  lines.push(`  - High: **${high}**`);
  lines.push(`  - Warning: **${warning}**`);
  lines.push(`  - Info: **${info}**`);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  // Findings by severity
  for (const severity of ["high", "warning", "info"] as const) {
    const group = report.findings.filter((f) => f.severity === severity);
    if (group.length === 0) continue;

    lines.push(`## ${SEVERITY_LABELS[severity]} Findings (${group.length})`);
    lines.push(``);
    for (const finding of group) {
      lines.push(`### [${finding.id}] ${finding.title}`);
      lines.push(``);
      lines.push(`**Type:** ${TYPE_LABELS[finding.type] ?? finding.type}`);
      lines.push(``);
      lines.push(finding.description);
      lines.push(``);
      if (finding.evidence) {
        lines.push(`**Evidence:** ${finding.evidence}`);
        lines.push(``);
      }
      lines.push(`**Recommended Action:** ${finding.recommendedAction}`);
      lines.push(``);
      if (finding.relatedFiles.length > 0) {
        lines.push(`**Related Files:**`);
        for (const file of finding.relatedFiles.slice(0, 6)) {
          lines.push(`- \`${file}\``);
        }
        lines.push(``);
      }
      lines.push(`**Human Approval Required:** ${finding.humanApprovalRequired ? "YES" : "NO"}`);
      lines.push(``);
      lines.push(`---`);
      lines.push(``);
    }
  }

  // Recommended updates
  lines.push(`## Recommended Documentation Updates`);
  lines.push(``);
  lines.push(`All recommended updates require human review and approval before being committed.`);
  lines.push(``);
  for (const update of report.recommendedDocUpdates) {
    lines.push(`### \`${update.targetPath}\``);
    lines.push(``);
    lines.push(`**Reason:** ${update.reason}`);
    lines.push(``);
    lines.push(`**Suggested Action:** ${update.suggestedAction}`);
    lines.push(``);
    lines.push(`**Human Approval Required:** YES`);
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(``);

  // Deferred items
  lines.push(`## Deferred Documentation Items`);
  lines.push(``);
  for (const item of report.deferredItems) {
    lines.push(`- ${item}`);
  }
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  // Human approval checklist
  lines.push(`## Human Approval Checklist`);
  lines.push(``);
  lines.push(`Before committing any recommended documentation changes:`);
  lines.push(``);
  lines.push(`- [ ] Review all HIGH findings and determine if immediate action is needed.`);
  lines.push(`- [ ] Review all WARNING findings for documentation stale risk.`);
  lines.push(`- [ ] Confirm which recommended doc updates should be created in the next slice.`);
  lines.push(`- [ ] Approve or reject each recommended update before committing.`);
  lines.push(`- [ ] Confirm no secrets, runtime data, or private information is included in proposed docs.`);
  lines.push(`- [ ] Update ROADMAP.md to reflect shipped features.`);
  lines.push(`- [ ] Update DECISIONS.md for new architectural decisions.`);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);
  lines.push(`*This report was generated by the FullSendOS Self-Documentation Review System. It is advisory only. Human approval is required before any changes are committed.*`);

  return lines.join("\n");
}
