import { jsonrepair } from "jsonrepair";

function stripCodeFences(text) {
  return String(text)
    .trim()
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```$/, "");
}

function extractLikelyJsonObject(text) {
  const firstBrace = text.indexOf("{");
  const lastBrace = text.lastIndexOf("}");
  if (firstBrace >= 0 && lastBrace > firstBrace) {
    return text.slice(firstBrace, lastBrace + 1);
  }
  return text;
}

function ensurePlainObject(value) {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error("Model output must be a JSON object.");
  }
  return value;
}

export function parseJsonObject(text) {
  const cleaned = stripCodeFences(text);
  const extracted = extractLikelyJsonObject(cleaned);

  try {
    return ensurePlainObject(JSON.parse(extracted));
  } catch (firstError) {
    try {
      // Repair near-valid JSON generated by model outputs (e.g., trailing commas, broken quotes).
      return ensurePlainObject(JSON.parse(jsonrepair(extracted)));
    } catch {
      if (extracted !== cleaned) {
        return ensurePlainObject(JSON.parse(jsonrepair(cleaned)));
      }
      throw firstError;
    }
  }
}
